### ISSUE TITLE
Error on Laravel 5.2

### ISSUE THREAD

**Issue by yuriandradd** [ytake/Laravel-Couchbase#15]
Hi,
Before installing on Laravel 5.2 i have error
CouchbaseConnector.php line 35.
 Class 'CouchbaseCluster' not found 
 Do you see anything like this?
Tks

**Comment by ytake** [comment]
required php-couchbase extension
[php-couchbase](https://github.com/couchbase/php-couchbase/)

example(CentOS 7)

```
$ sudo yum install -y libcouchbase libcouchbase-devel
$ git clone git@github.com:brett19/php-couchbase.git
$ cd php-couchbase
$ phpize && ./configure --with-couchbase
$ make && make install
```

You will add the couchbase.so extension to your php.ini file.
