### ISSUE TITLE
tags()->flush() does not work

### ISSUE THREAD

**Issue by delatbabel** [ytake/Laravel-Couchbase#16]
Hi,

I built this sample app with a Laravel console command: https://github.com/delatbabel/cachetest

After I put exception handlers into LegacyCouchbaseStore in the forever() and forget() functions (otherwise forget() throws an exception trying to forget a key that does not exist), I am still having one issue.  In the Cache tag forget test I am doing this:

``` php
Cache::tags(['testone', 'testtwo'])->put('testthree', $random_value, 60);
Cache::tags(['testone', 'testtwo'])->flush();
$value_to_check = Cache::tags(['testone', 'testtwo'])->get('testthree');
```

and it appears that the flush() does nothing because I can still retrieve the value using get() after it has been flushed().

Testing against memcached and redis caches does not show the same issue.

**Comment by ytake** [comment]
please use 0.2.1

**Comment by delatbabel** [comment]
Hi, I updated to version 0.2.1 but this doesn't appear to have helped. I have verified that I have libcouchbase 2.5.8 and also php-pecl-couchbase v2.2.0-beta2 installed from the sources but I get the same error.
