### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by spayder** [ytake/Laravel-Couchbase#4]
Can you provide some basic usage examples please? I've added CouchbaseServiceProvider to the providers and not sure how to use it.
Now I do the following:

```
$query = 'SELECT * FROM `beer-sample` where type="beer" LIMIT 50';
$res = DB::connection()->bucket('beer-sample')->select($query);
```

and just wondering if there is some better way to make a query. Thanks

**Comment by Ricardogolosito** [comment]
Great job! 
How could I set bucket access password?

**Comment by ytake** [comment]
@spayder Did you create Global Secondary Indexes(gsi)?

**Comment by ytake** [comment]
@Ricardogolosito 

example

``` php
$connection = \DB::connection('couchbase');
$connection->setBucketPassword('bucketPassword');
$connection->table('testing')->key($key)->insert($value);
```
